### ISSUE TITLE
Update descriptions for Alert Processing Rules

### ISSUE THREAD

**Issue by tulpy** [Azure/alz-monitor#143]
First of all great initiative on bringing Platform Observability to ALZ it is much needed.

A small change for the Alert processing rule description in the various files, it talks to the initiative when it should just be a Policy Definition

![image](https://user-images.githubusercontent.com/32761538/235926325-175e4085-ac3c-413a-ac0f-b2cbd6526c3c.png)

**Comment by paulgrimley** [comment]
@tulpy thanks for the feedback, assigning to @jfaurskov for review

**Comment by jfaurskov** [comment]
@tulpy thank you for your kind words. With #141 I believe that this has been remedied. Please let us know anything else you would like to see :-)
