### ISSUE TITLE
Incorrect deployment name in deploy-activitylog-NSG-Del

### ISSUE THREAD

**Issue by JoshuaMcConnaughey** [Azure/alz-monitor#150]
Minor display issue I noticed today:

Both the bicep and json versions of deploy-activitylog-NSG-Del have the deployment name set to "ActivityLAWorkspaceDelete" instead of "ActivityNSGDelete":

![image](https://github.com/Azure/alz-monitor/assets/122932140/c077b19e-99cf-4f9c-a6d0-01f74f6769d6)

![image](https://github.com/Azure/alz-monitor/assets/122932140/578c7ba4-03e0-47c9-b6d7-de5688487dbb)

**Comment by jfaurskov** [comment]
Thank you @JoshuaMcConnaughey, we will get that fixed in an upcoming refresh. If you want, feel free to create a PR with suggestions for change?
