### ISSUE TITLE
Missing connectivity alerts

### ISSUE THREAD

**Issue by erjosito** [Azure/alz-monitor#153]
Hey hey!

First of all, great job with this repo, this was sorely missing since years now!

We might want to define additional alerts for connectivity:
- ALB:
  - Data Path Availability
  - Health Probe Status
  - Used SNAT Ports (although this one wouldn't be required if the customer is following best practices and using NAT GW, but not all customers follow best practices :-) )
- ER Direct:
  - LineProtocol
  - RxLightLevel
  - TxLightLevel

If wanted, I can look into this and send a PR

**Comment by paulgrimley** [comment]
@erjosito welcome your contributions here so please do raise a PR with these if you can contribute - thanks!

**Comment by paulgrimley** [comment]
@erjosito, @mrajess is going to pick up doing this work

**Comment by mrajess** [comment]
Submitted PR #162 to address the ALB health alerts. I'm working on the ERD alerts now. I should have them done soon, but will need review as I'm not 100% sure on what the alert conditions should be, but I did follow published documentation on what healthy thresholds look like.

**Comment by erjosito** [comment]
Thanks a lot @mrajess !

**Comment by bzabber** [comment]
@mrajess Do you have a link to the documentation which recommends these alerts? I've looked a bit at what learn.microsoft.com has for ALB alerts and I came across this: https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-standard-diagnostics#how-do-i-check-my-snat-port-usage-and-allocation.
I can add the entries to the alertdetails.md table for you, if you can provide me with links to the documentation on why the thresholds you have should be used.
