### ISSUE TITLE
Custom Policies deploy without respective "Category" populated

### ISSUE THREAD

**Issue by pkorolo** [Azure/alz-monitor#173]
If one deploys by the guidance (in my case via "cli"), all Custom Policies deploy *without* the "Category" field populated.

Evidence from test deployment:

![image](https://github.com/Azure/alz-monitor/assets/60117125/11148cf6-707e-448a-a862-fe017869743c)

Most possibly due to the fact, that in the source code, "Category" in "metadata" is with *capital* "C", as seen here:

![image](https://github.com/Azure/alz-monitor/assets/60117125/380121f8-e002-4f7d-ad86-f3c923d4dfb0)

I think it should be "category" in the code (that is with *lowercase* "c".

**Comment by jfaurskov** [comment]
bug [29112](https://dev.azure.com/csuSolEng/Azure%20Landing%20Zones/_workitems/edit/29112) created
