### ISSUE TITLE
Management Group Structure graphic links "broken" in wiki

### ISSUE THREAD

**Issue by pkorolo** [Azure/alz-monitor#174]
- links in wiki view "https://github.com/Azure/alz-monitor/wiki/Introduction-to-deploying-ALZ-Monitor" seem broken, but

- links in view "https://github.com/Azure/alz-monitor/blob/main/docs/wiki/Introduction-to-deploying-ALZ-Monitor.md" work just fine

**Comment by arjenhuitema** [comment]
Thank you @pkorolo. Issue is still present; however, the impact has been mitigated, the images and other links are working again. We will be reviewing a permanent solution over the upcoming days.

**Comment by pkorolo** [comment]
@arjenhuitema PR ready for this to be fixed in wiki view:

https://github.com/Azure/alz-monitor/pull/176

**Comment by arjenhuitema** [comment]
Great work! Thank you! I´ll review/approve the changes now.
