### ISSUE TITLE
Missing Policy Definition for Management Monitor

### ISSUE THREAD

**Issue by benoitmonnier** [Azure/alz-monitor#193]
Hello,

When I deploy policy initiatives from the json file, ALZ-MonitorManagement.json , I get the following errors:

New-AzManagementGroupDeployment : 14:10:52 - Deployment 'ALZ-MonitorManagement' failed with error(s). Displaying 1 of 1 error(s).
Status message: The 'Alerting-Management' policy set definition request is invalid. The following policy definition could not be found:
'/providers/Microsoft.Management/managementGroups/mg/providers/Microsoft.Authorization/policyDefinitions/Deploy_RecoveryVault_BackupHealth_Alert'. (Code:PolicyDefinitionNotFound)
CorrelationId: 76150c09-5594-4e2b-b82d-f072d4e9fcb1

For the other json , everything works fine 

Thanks for your help

**Comment by paulgrimley** [comment]
Hi @benoitmonnier, thank you for raising this, let me speak with one of the team to look into this and come back to you @Alboroni @arjenhuitema @jfaurskov

**Comment by jfaurskov** [comment]
Hi @benoitmonnier thank you for raising the issue. We are fixing this in #190, @paulgrimley FYI

**Comment by antoniodurans** [comment]
I have the same error; I have the impression that it is related to the name.
alz-monitor-main> az deployment mg create --template-file ./src/resources/Microsoft.Authorization/policySetDefinitions/ALZ-MonitorManagement.json --location $location --management-group-id $pseudoRootManagementGroup

{"status":"Failed","error":{"code":"DeploymentFailed","target":"/providers/Microsoft.Management/managementGroups/ALZ/providers/Microsoft.Resources/deployments/ALZ-MonitorManagement","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"PolicyDefinitionNotFound","message":"The policy set definition 'Alerting-Management' request is invalid. The following policy definition could not be found: '/providers/Microsoft.Management/managementGroups/ALZ/providers/Microsoft.Authorization/policyDefinitions/**Deploy_RecoveryVault_BackupHealth_Alert**'."}]}}

![image](https://github.com/Azure/alz-monitor/assets/24736878/72d54de6-80cb-48f7-ae6d-060a2c59adc3)
