### ISSUE TITLE
ALZ Monitoring Alerts for Management

### ISSUE THREAD

**Issue by gerrynicol** [Azure/alz-monitor#200]
HI All,

When I deploy this through Azure Devops, it runs sucessfully, but the Policy Assignment at the 'Management' Management Group Scope isnt working. The definition gets created but the assignment isnt made. Updated the sample-pipeline.yml with the correct MG Id's and also the parameters-complete-management.json. Any ideas?

**Comment by MariaBTV** [comment]
Hi @gerrynicol, I had a similar issue this morning. Fixed it by amending the parameters-complete-management.json file. You can see the changes in my pull request: https://github.com/Azure/alz-monitor/pull/202/files

**Comment by gerrynicol** [comment]
Hi @MariaBTV. Thanks for that. I made the same changes after doing further investigation and all working now :)

**Comment by paulgrimley** [comment]
@gerrynicol @MariaBTV thank you so much for your contributions and findings - we really appreciate it! we actually have a PR in for this that hopefully will be merged shortly #201.  @arjenhuitema

**Comment by arjenhuitema** [comment]
Thank you for sharing your findings. Really appreciate it. PR201 is now merged. If there´s anything else please let us know.
