### ISSUE TITLE
Include definitions in native format

### ISSUE THREAD

**Issue by GitHubUser1339** [Azure/alz-monitor#205]
First of all I'd like to mention that this is a great initiative and a valuable addition to ALZ.

As an enterprise customer, we'd like to start evaluation of these policies in our engineering environment. The first issue however is that all Policy (Set) definitions are in Bicep and ARM format. We're using the [Enterprise Policy as Code](https://aka.ms/epac) solution to manage our policies at scale and are now more or less forced to implement an additional solution to deploy monitoring policies. 

I'd like to see the definitions in native json format so we can manage the policies with our existing solution.

**Comment by paulgrimley** [comment]
@GitHubUser1339 really appreciate your feedback and request here. We actually plan to move the repo to Azure landing zone (https://github.com/Azure/Enterprise-Scale/ ) so this can become part of the default architecture deployment. As part of this we will be creating native json policy format that can be consumed (regardless of being ALZ aligned or not). 

We anticipate this will be complete by end of August, please do check back on a regular basis for updates or watch the repo for notification of changes.

**Comment by paulgrimley** [comment]
@GitHubUser1339 we're changed direction since my post above but have addressed your ask. We're archiving this repo please visit aka.ms/amba for the new location and format you required.
