### ISSUE TITLE
missing parameter

### ISSUE THREAD

**Issue by DevanshuSyk** [Azure/alz-monitor#207]
#Deploy only the required policy definitions for the Service Health initiative
  New-AzManagementGroupDeployment -ManagementGroupId $pseudoRootManagementGroup -Location $location ./src/resources/Microsoft.Authorization/policyDefinitions/deploy-activitylog-ResourceHealth-UnHealthly-alert.bicep
  New-AzManagementGroupDeployment -ManagementGroupId $pseudoRootManagementGroup -Location $location ./src/resources/Microsoft.Authorization/policyDefinitions/deploy-activitylog-ServiceHealth-Health.bicep
  New-AzManagementGroupDeployment -ManagementGroupId $pseudoRootManagementGroup -Location $location ./src/resources/Microsoft.Authorization/policyDefinitions/deploy-activitylog-ServiceHealth-Incident.bicep 
  New-AzManagementGroupDeployment -ManagementGroupId $pseudoRootManagementGroup -Location $location ./src/resources/Microsoft.Authorization/policyDefinitions/deploy-activitylog-ServiceHealth-Maintenance.bicep
  New-AzManagementGroupDeployment -ManagementGroupId $pseudoRootManagementGroup -Location $location ./src/resources/Microsoft.Authorization/policyDefinitions/deploy-activitylog-ServiceHealth-Security.bicep
  New-AzManagementGroupDeployment -ManagementGroupId $pseudoRootManagementGroup -Location $location ./src/resources/Microsoft.Authorization/policyDefinitions/deploy-alertprocessingrule-deploy.bicep

the commands are missing parameter " -TemplateFile "

**Comment by paulgrimley** [comment]
Fixed with #208
