### ISSUE TITLE
Add displayName for Parameters in Policies Initiatives

### ISSUE THREAD

**Issue by SeSeicht** [Azure/alz-monitor#209]
Without setting the displayName (metadata) for the parameters of a Policy Set Definition for example looks like that in the Azure Portal:

![image](https://github.com/Azure/alz-monitor/assets/48480298/0c177b9e-7898-4d8d-80b5-fd1942504d09)

**Comment by paulgrimley** [comment]
Thanks @SeSeicht for raising this, we've captured on our internal backlog for planning.
