### ISSUE TITLE
Alert rules are missing action group

### ISSUE THREAD

**Issue by ThojoUno** [Azure/alz-monitor#210]
When I deploy Alz-monitor, the Alert rules are being created, but Action groups are not associated with the alert rule. Is this by design?

**Comment by paulgrimley** [comment]
Hi @ThojoUno have you deployed the latest release as I recall this was an issue in an earlier version we resolved (please update your fork if not and redeploy). If you have the latest version and its not working could you provide more details on what you have deployed (which initiatives). Thanks Paul.

**Comment by ThojoUno** [comment]
I am on an earlier release, I'll update and redeploy. Thank you for the quick response!

**Comment by ThojoUno** [comment]
I am still seeing the issue in the latest release in a brownfield implementation. I will test in a greenfield lab this weekend and see if I can replicate the issue...

**Comment by paulgrimley** [comment]
@ThojoUno just wanted to advise that Action Groups are not associated with alert rules directly, we have Alert Processing Rules which flows through to Action Groups. We are working on a Visio diagram which should help visualise this. 

Does that help clarify why you are not seeing Action Groups?
