### ISSUE TITLE
Select specific regions for Service Health Alerts

### ISSUE THREAD

**Issue by gerrynicol** [Azure/alz-monitor#214]
Would it be possible to have this as an option . To specfiy only certain regions to be alerted on for any service health alerts, possibly by using parameters to overvide all regions.

**Comment by paulgrimley** [comment]
@gerrynicol thank you for submitting this and its a valid ask, I'm adding to the backlog for consideration and will keep you posted.

**Comment by paulgrimley** [comment]
@gerrynicol I have been having conversations with numerous product teams on this and there are a couple of things to consider:
- Whilst in the current configuration for AMBA you enable all regions you only actually are notified on regions where you have resources in the event of a notification
- With that in mind it is not recommended to select specific regions as this could cause issues when new regions come onboard and you haven't updated this manually in your configuration.

With the above in mind I don't feel we should provide the ability to select specific regions balancing out the pros and cons.

Hope that helps share my conclusion and thanks for bringing this up, feel free to follow-up if I have missed something.
