### ISSUE TITLE
Metadata missing from VM Alerting Templates

### ISSUE THREAD

**Issue by kotom541** [Azure/alz-monitor#217]
The following definitions do not contain the "_deployed_by_alz_monitor": "True" metadata, meaning when running the Start-ALZMonitorCleanup.ps1 script they will not be removed.

Deploy VM Network Read Alert
Deploy VM Network Write Alert
Deploy VM CPU Alert
Deploy VM Data Disk Wite Latency Alert
Deploy VM OS Disk Space Alert
Deploy VM Data Disk Read Latency Alert
Deploy VM Data Disk Space Alert
Deploy VM OS Disk Write Latency Alert
Deploy VM OS Disk Read Latency Alert
Deploy VM HeartBeat Alert
Deploy VM Memory Alert

**Comment by arjenhuitema** [comment]
Hi @kotom541, thank you submitting the issue. I´ll review and add the missing metadata.

**Comment by arjenhuitema** [comment]
@kotom541 submitted a PR including the fix. 

Once that is merged you can sync your fork and redeploy the policy definitions.
