### ISSUE TITLE
Wiki mixup of available memory metric alert and memory percentage scheduled query alert

### ISSUE THREAD

**Issue by Dklaaborg** [Azure/alz-monitor#245]
There is something amiss with the wiki section Alerts Details regarding the first VM Insight Log Alert available memory. I think the metric version and the scheduled query version have been mixed together.
The threshold of 1000 and the name of the alert '[DINE] Deploy VM Available Memory Alert' matches the metric alert. The link from the name redirects to the correct scheduled query alert 'Deploy-vm-PercentMemory_alert.bicep'.
The threshold in the deployment is set to 10 and not 1000 as described in wiki, which would mean throwing an alert when a resource has less than 10% available memory. 

https://github.com/Azure/alz-monitor/blob/main/docs/wiki/AlertsDetails.md#vm-insights-log-alerts 

Possible fix:
The name of the alert should be changed to match the scheduled query.
The threshold of 1000 in wiki should be changed to 10.

**Comment by paulgrimley** [comment]
Thanks for letting us know @Dklaaborg, @bzabber can you take a look

**Comment by paulgrimley** [comment]
This has been resolved in the new repo @Dklaaborg aka.ms/amba/alz/
